version: "3"
services:
  phptriage:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/srv/app/public
    
    #Code that allows us to share "secret info"
    env_file:
      - ./docker/env